#!/bin/bash
set -eo pipefail

export $(xargs < {clickhouse_home}/server.properties)
export $(xargs < {clickhouse_home}/user.properties)

# copy configs

cp {clickhouse_home}/config_template.xml {clickhouse_main_config_path}

space_4="    "

## zookeeper config
zk_address_list=($(echo ${zookeeper_nodes} | tr "," "\n" | sort | uniq))
zookeeper_replace_str=""
for zk_address in ${zk_address_list[@]}
do
    IFS=':' read -r -a zk_split_list <<< $zk_address
    zk_host=${zk_split_list[0]}
    zk_port=${zk_split_list[1]}
    zookeeper_replace_str="${zookeeper_replace_str}\n$space_4$space_4<node>"
    zookeeper_replace_str="${zookeeper_replace_str}\n$space_4$space_4$space_4<host>$zk_host</host>"
    zookeeper_replace_str="${zookeeper_replace_str}\n$space_4$space_4$space_4<port>$zk_port</port>"
    zookeeper_replace_str="${zookeeper_replace_str}\n$space_4$space_4</node>"
done
zookeeper_replace_str="$zookeeper_replace_str\n$space_4"

sed -i "s#{zookeeper_replace_str}#${zookeeper_replace_str}#g" {clickhouse_main_config_path}

## replica config
node_list=($(echo ${nodes} | tr "," "\n" | sort | uniq))
local_ip=`ifconfig eth0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
local_hostname=`hostname`
current_node_no=0
for i in ${!node_list[@]};
do
    if [ ${node_list[$i]} == ${local_ip} ] || [ ${node_list[$i]} == ${local_hostname} ]; then
        current_node_no=$i
        break
    fi
done

replica_num=`echo "${#node_list[@]} - 1" | bc`
current_node_no=$(printf "%02d" $current_node_no)
remote_cluster_name=${cluster_name}_${#node_list[@]}_shards_2replicas

## default: shard count: same as node count; replica count: 2
remote_cluster_def=""
for i in ${!node_list[@]};
do
    next_node=""
    if [[ $i -lt $((${#node_list[@]}-1)) ]]; then
        next_node=${node_list[$i+1]}
    else
        next_node=${node_list[0]}
    fi
    replica_node_arr=(${node_list[$i]} ${next_node})

    node_num_str=$(printf "%02d" $((i+1)))
    
    database_num="${init_database_name}$node_num_str"
    remote_cluster_def="$remote_cluster_def\n$space_4$space_4$space_4<shard>"
    remote_cluster_def="$remote_cluster_def\n$space_4$space_4$space_4$space_4<internal_replication>true</internal_replication>"
    for replica_node in ${replica_node_arr[@]}
    do
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4<replica>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4$space_4<default_database>$database_num</default_database>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4$space_4<host>$replica_node</host>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4$space_4<port>${server_tcp_port}</port>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4$space_4<user>${default_user_name}</user>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4$space_4<password>${default_user_password}</password>"
        remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4$space_4</replica>"
    done
    remote_cluster_def="${remote_cluster_def}\n$space_4$space_4$space_4</shard>"
done

sed -i "s#{remote_cluster_name}#${remote_cluster_name}#g" {clickhouse_main_config_path}
sed -i "s#{remote_cluster_def}#${remote_cluster_def}#g" {clickhouse_main_config_path}

sed -i "s#{shard_no}#${current_node_no}#g" {clickhouse_main_config_path}
sed -i "s#{replica_no}#${current_node_no}#g" {clickhouse_main_config_path}

## user config
cp {clickhouse_home}/users_config_template.xml {clickhouse_user_config_path}

normal_user_arr=${normal_user}
normal_user_password_arr=${normal_user_password}
normal_user_allow_databases_arr=${normal_user_allow_database}

if [[ ${normal_user} == *";"* ]]; then
    normal_user_arr=($(echo ${normal_user} | tr ";" "\n"))
    normal_user_password_arr=($(echo ${normal_user_password} | tr ";" "\n"))
    normal_user_allow_databases_arr=($(echo ${normal_user_allow_database} | tr ";" "\n"))
fi

normal_user_def=""
for index in ${!normal_user_arr[@]}
do
    normal_user=${normal_user_arr[${index}]}
    normal_user_password=${normal_user_password_arr[${index}]}
    normal_user_allow_databases=${normal_user_allow_databases_arr[${index}]}

    normal_user_def="${normal_user_def}\n$space_4$space_4<$normal_user>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4<password>$normal_user_password</password>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4<profile>default</profile>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4<quota>default</quota>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4<networks>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4$space_4<ip>::/0</ip>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4</networks>"
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4<allow_databases>"
    allow_database_list=($(echo $normal_user_allow_databases | tr "," "\n" | sort | uniq))
    for allow_database in ${allow_database_list[@]}
    do
        normal_user_def="${normal_user_def}\n$space_4$space_4$space_4$space_4<database>${allow_database}</database>"
    done
    normal_user_def="${normal_user_def}\n$space_4$space_4$space_4</allow_databases>"
    normal_user_def="${normal_user_def}\n$space_4$space_4</$normal_user>"
done

sed -i "s#{normal_user_def}#${normal_user_def}#g" {clickhouse_user_config_path}

## other envs
env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" {clickhouse_main_config_path}
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" {clickhouse_user_config_path}
done

chown clickhouse:clickhouse {clickhouse_main_config_path}
chown clickhouse:clickhouse {clickhouse_user_config_path}