route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: test
  routes:
  - receiver: 'test'
    match:
      tag: test
  {routes}

receivers:
  - name: 'test'
  {receivers}

