NET_CN ?= FALSE

# git
github_url := https://github.com
github_repo := https://github.com

# python
pip_repo := https://pypi.org/simple

# other common var
modules_home := /opt/modules

ifeq "${NET_CN}" "TRUE"
# git
github_url := https://hub.fastgit.xyz
github_repo = https://download.fastgit.org

# python
pip_repo := https://pypi.mirrors.ustc.edu.cn/simple
endif
