#!/bin/bash
set -eo pipefail

pushd {kafka_home}/config

export $(xargs < kafka.properties)

cp server.properties_template server.properties

export local_ip=`ifconfig eth0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
local_hostname=`hostname`

host_list=($(echo ${installed_hosts} | tr "," "\n"))
start_index=${broker_start_id}
local_index=0
for current_host in ${host_list[@]}
do
    if [ "${current_host}" = "${local_hostname}" ] ; then
        local_index=${start_index}
        break
    fi
    start_index=$((start_index+1))
done

export broker_id=${local_index}

# other envs
env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" server.properties
done

popd