#!/bin/bash
set -eo pipefail

pushd {grafana_home}/conf

export $(xargs < grafana.properties)

cp custom.ini.template custom.ini

env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" custom.ini
done

popd