#!/bin/bash
set -eo pipefail

export $(xargs < {zookeeper_home}/conf/zookeeper.properties)

# create zookeeper data dir if not exist
mkdir -p ${data_dir}

pushd {zookeeper_home}/conf

# init zookeeper config
zk_config_file=zoo.cfg
cp -f zoo_cluster_template.cfg ${zk_config_file}

local_ip=`ifconfig eth0 | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
local_hostname=`hostname`

node_list=($(echo ${servers} | tr "," "\n"))
index=1
local_index=1
server_info=""
for current_node in ${node_list[@]}
do
    server_info="${server_info}\nserver.$index=${current_node}"
    if [[ "${current_node}" =~ ^${local_ip}.* ]] || [[ "${current_node}" =~ ^${local_hostname}.* ]] ; then
        local_index=${index}
    fi
    index=$((index+1))
done
sed -i "s/{server_info}/${server_info}/g" ${zk_config_file}

# myid
echo "${local_index}" > ${data_dir}/myid

# other envs
env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" zoo.cfg
done

popd