#!/bin/bash
set -eo pipefail

pushd {jupyterhub_config_home}

export $(xargs < {jupyterhub_config_home}/jupyterhub.properties)

cp jupyterhub_config_template.py jupyterhub_config.py

mkdir -p ${jupyterhub_share_path}

# init jupyter config
env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" jupyterhub_config.py
done

# init jupyter user conf (maybe need)

popd