#!/bin/bash
set -eo pipefail

pushd {alertmanager_home}

export $(xargs < alertmanager.properties)

cp alertmanager_template.yml alertmanager.yml

env_keys=`printenv | sed "s#=.*##g"`
for current_env_key in ${env_keys[@]}
do
    sed -i "s#{${current_env_key}}#${!current_env_key}#g" alertmanager.yml
done

# alertmanager
export alertmanager=""

export routes=""
export receivers=""

popd
